language: haskell
ghc: 7.8
cabal: 1.20
branches:
  only:
  - source
env:
  global:
  - GH_NAME="Travis on behalf of IMOKURI"
  - secure: "iw7zkk4s3JZoZ9rqL9Fe43TcnGVJ4eTURgIxS2f0swsdpo/zZ9i5tiZ/QrZtRioOLjwwe3TNrJehWQrEv2oMy+By5a4c9NI4gMmCRlps3IGvW8SEFEoelaMqM4HZB/eXPZkhKyqf7LpGz3oC2HAH65u6Z9UfPchjsKJ8QmGTW4w="
  - secure: "PJdQbveUtenH0lFV5oOOYsBBMwGKEZ7QsnEmtHLyeCb4KNvslA3J7DUn5tBMJa8Zczz7ZiTEuwHPE0CwUZAwht7gOKbnPwMgK+CtB4RcV1rvEvJpCl6y2OuIQ6tP35zZ6Ox6QVAB4yN7+XALeXCLk/9n0yZPQ77rTWBrHvaRxMM="
before_install:
- git submodule foreach --recursive 'git checkout master; git ls-files | grep -v README | grep -v CNAME | xargs -r git rm'
- cabal install cabal-install && cabal --version
install:
- cabal sandbox init
- cabal install -j --only-dependencies --disable-documentation
- cabal configure --disable-library-profiling --disable-tests --disable-library-coverage --disable-benchmarks --disable-split-objs
before_script:
- git config --global user.name "$GH_NAME"
- git config --global user.email "$GH_EMAIL"
script: cabal run -j build
after_script:
- cd _site
- export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
- git remote add github https://${GH_TOKEN}@${REMOTE}
- git add --all
- git status
- git commit -m "Built by Travis ( build $TRAVIS_BUILD_NUMBER )"
- git push github master:master | grep -v http
