language: c

sudo: false
cache:
  directories:
    - $HOME/.stack

branches:
  except:
    - master

env:
  global:
    - GH_NAME="Travis on behalf of IMOKURI"
    - secure: "iw7zkk4s3JZoZ9rqL9Fe43TcnGVJ4eTURgIxS2f0swsdpo/zZ9i5tiZ/QrZtRioOLjwwe3TNrJehWQrEv2oMy+By5a4c9NI4gMmCRlps3IGvW8SEFEoelaMqM4HZB/eXPZkhKyqf7LpGz3oC2HAH65u6Z9UfPchjsKJ8QmGTW4w="
    - secure: "EEyVgOpE1zUfNnDnVNGUD2smgwTxYoSNlALQZGmvXDNJhwzkXR0IIfxLEotGIoiiZYVQY6Wq4ZvdfAa7kz7IEiOIughH2doywTQtSGlmVJbFn8XUF+3n/j/yPexFzayCPbIvQ9fv9iZzzmHgsoXEUGTdlGaEhkI8YYHEh+/HiS8="

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - git submodule foreach git checkout master

install:
  - stack --no-terminal setup
  - stack --no-terminal build

before_script:
  - git config --global user.name "$GH_NAME"
  - git config --global user.email "$GH_EMAIL"

script:
  - make rebuild

after_success:
  - test "$TRAVIS_BRANCH" == "source" \
    && test "$TRAVIS_PULL_REQUEST" == "false" \
    && cd _site \
    && ! git diff-index --quiet HEAD \
    && export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///') \
    && git remote add github https://${GH_TOKEN}@${REMOTE} \
    && git add --all \
    && git status \
    && git commit -m "Built by Travis ( build $TRAVIS_BUILD_NUMBER )" \
    && git push github master:master 2>&1 | grep -v http

notifications:
  email: false
